// This file should be generated by running:
// firebase_cli generate config-dart

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Replace with your Firebase configuration
    // You can get this from your Firebase Console

    return const FirebaseOptions(
      apiKey: 'AIzaSyDxxxxxxxxxxxxxxxxxxxxxxxxx',
      appId: '1:123456789:android:xxxxxxxxxxxxxxxxx',
      messagingSenderId: '123456789',
      projectId: 'her-cycle-xxxxx',
      storageBucket: 'her-cycle-xxxxx.appspot.com',
      iosBundleId: 'com.example.herCycle',
    );
  }
}
